#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 23 23:54:09 2021

@author: rh.hayden
Title: Recursion
"""
#Tail Recursion - The recursive funciton is the last thing we do or last step

#Defining the function
def TakeOneDown(bottlesOfTea):
    if(bottlesOfTea==0):
        #Base Case
        print(bottlesOfTea, "Bottles of tea left on the wall. You are all out.")
    else:
        print(bottlesOfTea, "Bottles of tea left on the wall.")
        #Recursion set up below
        return TakeOneDown(bottlesOfTea-1)
    return bottlesOfTea

print("\n\nBottles of Tea Cutdown!")
TakeOneDown(99)

#Non-Tail Recursion

def TakeOneDownNT(cupsOfTea):
    if(cupsOfTea==0):
        #Base Case
        print(cupsOfTea, "Cups of tea left on the Wall.")
    else:
        return TakeOneDownNT(cupsOfTea-1)
        print(cupsOfTea, "Cups of tea left on the wall.")
    return cupsOfTea

print("\n\nCups of Tea Cutdown!")
TakeOneDownNT(99)
